import { Course } from "@/types/Course";

export const dummyCourses: Course[] = [
  {
    id: "course-1",
    username: "alice",
    user_id: "1",
    created_at: "2025-04-01T10:00:00Z",
    student_quantity: ["1", "6", "7"],
    title: "Introduction to Software Engineering",
    description: "Fundamentals of software development, processes, and project structure.",
    course_category: "Engineering",
    start_date: "2025-05-01",
    end_date: "2025-08-01",
    schedule: "Mon/Wed/Fri 10:00 AM - 11:30 AM",
    status: "approved"
  },
  {
    id: "course-2",
    username: "bob",
    user_id: "1",
    created_at: "2025-04-02T09:30:00Z",
    student_quantity: ["1", "6"],
    title: "Advanced Mathematics",
    description: "Exploration of algebra, geometry, and calculus.",
    course_category: "Math",
    start_date: "2025-05-03",
    end_date: "2025-07-30",
    schedule: "Tue/Thu 9:00 AM - 10:30 AM",
    status: "approved"
  },
  {
    id: "course-3",
    username: "clara",
    user_id: "1",
    created_at: "2025-04-03T11:00:00Z",
    student_quantity: ["8", "9"],
    title: "Graphic Design Basics",
    description: "Introduction to design principles and Adobe Illustrator.",
    course_category: "Art & Design",
    start_date: "2025-05-05",
    end_date: "2025-08-15",
    schedule: "Mon/Wed 1:00 PM - 2:30 PM",
    status: "approved"
  },
  {
    id: "course-4",
    username: "david",
    user_id: "4",
    created_at: "2025-04-04T14:00:00Z",
    student_quantity: [],
    title: "English Literature 101",
    description: "Reading and analyzing classic and modern literature.",
    course_category: "Literature",
    start_date: "2025-05-10",
    end_date: "2025-07-10",
    schedule: "Fri 2:00 PM - 4:00 PM",
    status: "pending"
  },
  {
    id: "course-5",
    username: "eva",
    user_id: "5",
    created_at: "2025-04-05T08:45:00Z",
    student_quantity: ["6", "7", "8"],
    title: "Artificial Intelligence Overview",
    description: "A non-technical intro to modern AI techniques and applications.",
    course_category: "Technology",
    start_date: "2025-05-15",
    end_date: "2025-09-01",
    schedule: "Tue/Thu 3:00 PM - 4:30 PM",
    status: "approved"
  },
  {
    id: "course-6",
    username: "alice",
    user_id: "1",
    created_at: "2025-04-06T12:00:00Z",
    student_quantity: [],
    title: "Agile Development Workshop",
    description: "Hands-on project work using Scrum and Agile principles.",
    course_category: "Engineering",
    start_date: "2025-06-01",
    end_date: "2025-07-15",
    schedule: "Sat 10:00 AM - 1:00 PM",
    status: "rejected"
  },
  {
    id: "course-7",
    username: "bob",
    user_id: "2",
    created_at: "2025-04-07T09:00:00Z",
    student_quantity: ["6"],
    title: "Geometry in Real Life",
    description: "Explore geometry applications in architecture and design.",
    course_category: "Math",
    start_date: "2025-06-05",
    end_date: "2025-08-10",
    schedule: "Wed 4:00 PM - 5:30 PM",
    status: "approved"
  },
  {
    id: "course-8",
    username: "clara",
    user_id: "3",
    created_at: "2025-04-08T13:15:00Z",
    student_quantity: ["7"],
    title: "Typography Fundamentals",
    description: "Understanding typefaces, kerning, and layout design.",
    course_category: "Art & Design",
    start_date: "2025-05-20",
    end_date: "2025-07-20",
    schedule: "Tue/Thu 10:00 AM - 11:30 AM",
    status: "approved"
  },
  {
    id: "course-9",
    username: "david",
    user_id: "4",
    created_at: "2025-04-09T15:00:00Z",
    student_quantity: [],
    title: "Creative Writing",
    description: "Writing compelling stories, poetry, and essays.",
    course_category: "Literature",
    start_date: "2025-05-25",
    end_date: "2025-07-25",
    schedule: "Mon 2:00 PM - 4:00 PM",
    status: "pending"
  },
  {
    id: "course-10",
    username: "eva",
    user_id: "5",
    created_at: "2025-04-10T10:30:00Z",
    student_quantity: ["6", "10"],
    title: "Intro to Machine Learning",
    description: "Beginner-friendly guide to supervised learning and models.",
    course_category: "Technology",
    start_date: "2025-06-10",
    end_date: "2025-09-10",
    schedule: "Fri 10:00 AM - 12:00 PM",
    status: "approved"
  }
];