export type Post = {
    postID: string,
    address: string,
    price: number,
    description: string,
    image: string[],
    property_type: string,
    area: string,
    house_type: string,
    documentation_list: string[],
    structural_material: number,
    environmental_resistance: number,
    maintenance_condition: number,
    age_score: number,
    verified_quality: number,
    final_score: number,
    township: string,
    title: string,
    user_id: number,
    isActive: boolean,
    isVerify: boolean,
    tour_service: number,
}